const storageKey = "rooster-next-robot-bound";
const products = [
  { id: "pork-rice", name: "猪脚饭", category: "主食", price: "12.95", tax: "Tax(10%)", printer: "厨房", devices: ["next-robot"] },
  { id: "kungpao-rice", name: "宫保鸡丁饭", category: "主食", price: "11.95", tax: "Tax(10%)", printer: "厨房", devices: ["next-robot"] },
  { id: "egg-rice", name: "番茄炒蛋饭", category: "主食", price: "10.95", tax: "Tax(10%)", printer: "厨房", devices: ["next-robot"] },
  { id: "mushroom-chicken", name: "香菇鸡饭", category: "主食", price: "10.95", tax: "Tax(10%)", printer: "厨房", devices: [] },
];
let selected = new Set(); let editingId = null;
const list = document.querySelector("#product-list-page"); const editor = document.querySelector("#product-editor");
const deviceOption = document.querySelector("#product-robot-option");
deviceOption.id = "product-device-option";
deviceOption.innerHTML = '<label class="routing-check"><input id="product-device-enabled" type="checkbox" />发送到智能设备</label><div id="product-device-options" class="route-card-list"><button class="route-card" data-device="next-robot" type="button">Next Robot</button></div>';
function bound() { return new URLSearchParams(location.search).get("bound") === "1" || localStorage.getItem(storageKey) === "true"; }
function toast(message) { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2200); }
function renderRows() { const term = document.querySelector("#product-search").value.trim(); const visible = products.filter((p) => p.name.includes(term)); const all = visible.length && visible.every((p) => selected.has(p.id)); const allButton = document.querySelector("#select-all-products"); allButton.classList.toggle("checked", all); document.querySelector("#delete-products").disabled = !selected.size; document.querySelector("#product-rows").innerHTML = visible.map((p) => `<article class="products-row ${selected.has(p.id) ? "selected" : ""}"><button class="list-check ${selected.has(p.id) ? "checked" : ""}" data-select="${p.id}" type="button" aria-label="选择 ${p.name}"></button><b>${p.name}</b><span>${p.category}</span><span class="color-chip"></span><span>$${p.price}</span><span>${p.tax}</span><span>${p.printer}</span><span class="status-switch"></span><button class="edit-link" data-edit="${p.id}" type="button" aria-label="编辑 ${p.name}">✎</button></article>`).join(""); }
function showEditor(id = null) { const p = products.find((item) => item.id === id); editingId = p?.id || null; document.querySelector("#product-name-en").value = p?.name || ""; document.querySelector("#product-name-zh").value = p?.name || ""; document.querySelector("#kitchen-name-en").value = p?.name || ""; document.querySelector("#kitchen-name-zh").value = p?.name || ""; document.querySelector("#product-pos-en").value = p?.name || ""; document.querySelector("#product-pos-zh").value = p?.name || ""; document.querySelector("#product-price").value = p?.price || ""; document.querySelector("#product-device-option").hidden = false; const enabled = Boolean(p?.devices?.length); document.querySelector("#product-device-enabled").checked = enabled; document.querySelectorAll("[data-device]").forEach((button) => button.classList.toggle("selected", Boolean(p?.devices?.includes(button.dataset.device)))); list.hidden = true; editor.hidden = false; document.querySelector("#return-pos").hidden = true; document.querySelector("#back-list").hidden = false; document.querySelector("#header-save").hidden = false; document.querySelector("#page-title").textContent = p ? "编辑商品" : "新增商品"; }
function showList() { list.hidden = false; editor.hidden = true; document.querySelector("#return-pos").hidden = false; document.querySelector("#back-list").hidden = true; document.querySelector("#header-save").hidden = true; document.querySelector("#page-title").textContent = "商品"; renderRows(); }
document.querySelector("#product-search").addEventListener("input", renderRows);
document.querySelector("#open-product-editor").addEventListener("click", () => showEditor());
document.querySelector("#back-list").addEventListener("click", showList);
document.querySelector("#product-rows").addEventListener("click", (event) => { const edit = event.target.closest("[data-edit]"); if (edit) return showEditor(edit.dataset.edit); const check = event.target.closest("[data-select]"); if (!check) return; selected.has(check.dataset.select) ? selected.delete(check.dataset.select) : selected.add(check.dataset.select); renderRows(); });
document.querySelector("#select-all-products").addEventListener("click", () => { const ids = products.filter((p) => p.name.includes(document.querySelector("#product-search").value.trim())).map((p) => p.id); const all = ids.length && ids.every((id) => selected.has(id)); ids.forEach((id) => all ? selected.delete(id) : selected.add(id)); renderRows(); });
document.querySelector("#delete-products").addEventListener("click", () => { for (let i = products.length - 1; i >= 0; i -= 1) if (selected.has(products[i].id)) products.splice(i, 1); selected = new Set(); renderRows(); toast("已删除所选商品"); });
document.querySelector("#product-device-options").addEventListener("click", (event) => { const button = event.target.closest("[data-device]"); if (button) button.classList.toggle("selected"); });
document.querySelector("#product-device-enabled").addEventListener("change", (event) => { document.querySelectorAll("[data-device]").forEach((button) => button.classList.toggle("selected", event.target.checked)); });
document.querySelector("#product-form").addEventListener("submit", (event) => { event.preventDefault(); const p = products.find((item) => item.id === editingId); if (p) { p.name = document.querySelector("#product-name-zh").value.trim(); p.price = document.querySelector("#product-price").value.trim(); p.devices = [...document.querySelectorAll("[data-device].selected")].map((button) => button.dataset.device); } showList(); toast("商品已保存"); });
renderRows();
